# Generated by Django 3.2 on 2021-06-04 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('insured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('main_town', models.CharField(max_length=50)),
                ('main_postal_code', models.CharField(max_length=7)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=1024)),
                ('driver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('ride_request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='passenger.riderequest')),
            ],
        ),
    ]
