# Generated by Django 3.2 on 2021-06-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='completed_ride',
            field=models.BooleanField(default=False),
        ),
    ]
