# Generated by Django 3.2 on 2021-06-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_auto_20210604_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='accepted_ride',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='comments',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='dropoff_postal_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='pickup_postal_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
