# Generated by Django 3.2 on 2021-06-07 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passenger', '0005_alter_riderequest_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='passenger',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
